# Generated by Django 5.0.3 on 2024-05-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_carinventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
